POST https://ajackus-usermanagementdashboard.onrender.com/users/
Content-Type: application/json

{
  "first_name": "latha",
  "last_name": "maram",
  "email": "lathmaram123@gmail.com",
  "department": "Home Maker"
}

###
GET https://ajackus-usermanagementdashboard.onrender.com/users/

###

GET https://ajackus-usermanagementdashboard.onrender.com/users/3

###

PUT https://ajackus-usermanagementdashboard.onrender.com/users/3
Content-Type: application/json

{
  "first_name": "Anitha Srivali",
  "last_name": "Kumar",
  "department": "HR"
}

###

DELETE https://ajackus-usermanagementdashboard.onrender.com/users/3